add new APM billing metrics to sf.org
signalfx/integrations pull request #899
Opened 2020-10-30 19:29 UTC by brianashby-sfx

- reorganize existing apm metrics
- add new apm metrics

2020-11-09 22:16 UTC, cbasavaiah-splunk approved these changes

2020-11-10 16:51 UTC, gergas3 commented on signalfx-org-metrics/metrics.yaml
> +  metric_type: gauge
this is a counter

2021-01-22 23:19 UTC, gergas3 requested changes

2021-01-22 23:19 UTC, gergas3 commented on signalfx-org-metrics/metrics.yaml
> +  brief: The number of bytes Splunk APM accepts for a span after decompression
`for a span` --> `from all ingested span data`
Not for _a_ span, but bytes of _all_ spans ingested

2021-01-22 23:19 UTC, gergas3 commented on signalfx-org-metrics/metrics.yaml
> +    from spans after decompression but before filtering and throttling.
`from spans` is also a good expression to use also with `sf.org.apm.numSpanBytesReceived`

2021-01-27 23:18 UTC, mdubbyap commented on signalfx-org-metrics/README.md.jinja
> +A `gross` metric reports the total number of MTS the system receives before any throttling or filtering kicks in.
these two lines are incorrectly using MTS. datapoints would be a better noun for those calls but these also exist for spans and rum Spans.

2021-01-27 23:18 UTC, mdubbyap commented on signalfx-org-metrics/metrics.yaml
> +    if there is no start time, trace ID, or service associated with it.
too many spans in trace is another reason we would increment invalid spans dropped.

2021-01-27 23:18 UTC, mdubbyap commented on signalfx-org-metrics/metrics.yaml
> +    A span can be invalid if there is no start time, trace ID, or service associated with it.
same as above.

2021-02-05 17:01 UTC, gergas3 approved these changes

2021-02-05 17:06 UTC, merged