remove deprecated org metric
signalfx/integrations pull request #923
Opened 2021-03-19 20:47 UTC by mstumpfx

this doesn't exist anymore

2021-03-23 17:48 UTC, jmalin-signalfx requested changes
See my comments.

2021-03-23 17:48 UTC, jmalin-signalfx commented on elastic-stack/README.md
> +Installation is actually configuring linking from property values on SignalFx charts and alerts to any URL-addressable destination.
To install, add a data link from an Infrastructure Monitoring chart or detector to a URL. To learn more, see the section
[Clicking on a property value to follow a link](https://docs.signalfx.com/en/latest/managing/data-links.html#clicking-on-a-property-value-to-follow-a-link) in the user documentation.

2021-03-23 17:48 UTC, jmalin-signalfx commented on elastic-stack/README.md
>  Read about the possible configurations [here](https://docs.signalfx.com/en/latest/dashboards/dashboard-links.html) and priority linking [here](https://docs.signalfx.com/en/latest/managing/data-links.
Unless this feature allows local data linking, or linking to a dashboard, Splunk, or Kibana, this sentence is unnecessary.

2021-03-23 17:48 UTC, jmalin-signalfx commented on elastic-stack/README.md
>  To read about creating local data links, click [here](https://docs.signalfx.com/en/latest/managing/data-links.html#local-links).
To learn more about creating local data links, see [Configuring local data links](https://docs.signalfx.com/en/latest/managing/data-links.html#configuring-local-data-links)

Does this feature work with local data links?

**NOTE**: The Splunk Documentation Style Guide specifies that link text for all links should be the same as the heading or sentence that is the link target. In particular, don't use "here" as link text.

2021-03-23 17:48 UTC, jmalin-signalfx commented on elastic-stack/README.md
> +To access Global Data Link configuration options page, click [here](/#/organization/YOUR_SIGNALFX_ORG_ID?selectedKeyValue=sf_section:globaldatalinks).
The link text doesn't conform to the Splunk Documentation Style Guide. See my previous comment.
The link target is not a valid URL.

2021-03-23 17:48 UTC, jmalin-signalfx commented on signalfx-org-metrics/README.md.jinja
> +   you’ve defined, use the metric `sf.org.numCustomMetrics`. To learn more about custom MTS, see the
The phrase "you’ve defined, use the metric `sf.org.numCustomMetrics`." is not a sentence.

2021-07-28 14:37 UTC, keitwb approved these changes

2021-07-28 14:40 UTC, merged